# Site settings
title: Scattered Notes
# email: sayan751@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My (opinionated) notes on various programming tools/languages that I use from time-to-time; basically whatever catches my fancy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://scattered-notes.netlify.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Sayan751
stackoverflow: 2270340/sayan-pal
comments: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-font-awesome
